import type { VocabularyFormData } from '../types/vocabulary.types';

export const getEmptyVocabularyFormData = (): VocabularyFormData => ({
  word: '',
  wordImageFilename: '',
  wordImageOriginalUrl: '',
  wordImageUploadMethod: 'url',
  simplePastTense: '',
  pastPerfectTense: '',
  translation: '',
  synonyms: '',
  pluralForm: '',
  phonetic: '',
  phoneticAudioFilename: '',
  phoneticAudioOriginalUrl: '',
  phoneticAudioUploadMethod: 'url',
  dictionaryUrl: '',
  partOfSpeech: '',
  definition: '',
  example: '',
  tags: '',
  lang: 'EN',
  displayOrder: 999,
  isActive: true,
  wordImageFile: null,
  phoneticAudioFile: null,
});
