import type { FreeTextQuestionRuFormData } from '../types/freeTextQuestionRu.types';

export const getEmptyFreeTextQuestionRuFormData = (): FreeTextQuestionRuFormData => ({
  question: '',
  answer: '',
  explanation: '',
  description: '',
  questiona: '',
  answera: '',
  questionb: '',
  answerb: '',
  questionc: '',
  answerc: '',
  questiond: '',
  answerd: '',
  questione: '',
  answere: '',
  questionf: '',
  answerf: '',
  failCount: undefined,
  successCount: undefined,
  difficultyLevel: '',
  tags: '',
  grammarChapter: '',
  scienceChapter: '',
  lang: 'EN',
  term: undefined,
  week: undefined,
  displayOrder: 999,
  isActive: true,
});
