import type { VocabularyRuFormData } from '../types/vocabularyRu.types';

export const getEmptyVocabularyRuFormData = (): VocabularyRuFormData => ({
  name: '',
  phonetic: '',
  partOfSpeech: '',
  nounPluralForm: '',
  nounForm: '',
  nounMeaning: '',
  nounExample: '',
  verbSimplePastTense: '',
  verbPastPerfectTense: '',
  verbPresentParticiple: '',
  adjectiveComparativeForm: '',
  adjectiveSuperlativeForm: '',
  verbForm: '',
  verbMeaning: '',
  verbExample: '',
  adjectiveForm: '',
  adjectiveMeaning: '',
  adjectiveExample: '',
  adverbForm: '',
  adverbMeaning: '',
  adverbExample: '',
  translation: '',
  synonyms: '',
  definition: '',
  example: '',
  dictionaryUrl: '',
  imageFilename: '',
  imageOriginalUrl: '',
  imageUploadMethod: 'url',
  phoneticAudioFilename: '',
  phoneticAudioOriginalUrl: '',
  phoneticAudioUploadMethod: 'url',
  tags: '',
  difficultyLevel: 'easy',
  lang: 'EN',
  displayOrder: 999,
  isActive: true,
  imageFile: null,
  phoneticAudioFile: null,
});
