import type { VocabularyRuFormData } from '../types/vocabularyRu.types';

export const getEmptyVocabularyRuFormData = (): VocabularyRuFormData => ({
  word: '',
  wordImageFilename: '',
  wordImageOriginalUrl: '',
  wordImageUploadMethod: 'url',
  simplePastTense: '',
  pastPerfectTense: '',
  translation: '',
  synonyms: '',
  pluralForm: '',
  phonetic: '',
  phoneticAudioFilename: '',
  phoneticAudioOriginalUrl: '',
  phoneticAudioUploadMethod: 'url',
  dictionaryUrl: '',
  partOfSpeech: '',
  definition: '',
  example: '',
  tags: '',
  lang: 'EN',
  difficultyLevel: 'easy',
  displayOrder: 999,
  isActive: true,
  wordImageFile: null,
  phoneticAudioFile: null,
});
